### ISSUE TITLE
Validations Priority 3: XML links

### ISSUE THREAD

**Issue by 5annaha** [spatineo/kaatio-planvalidator#3]
- [ ] Check links are working

Check the target of the link exists (`xlink:href="#planner-mka"` --> `gml:id="planner-mka"`)

**NOTICE** Link checking should be combined with ID generations since this changes the ID's. #4 

* Save all the `gml:id` to a dict and then it is easy to check if the link target can be found from the dict 
* This same dict can be used to generate new IDs --> has both old and new IDs --> Easy to replace old ID with the new ID

**Comment by ilkkarinne** [comment]
Errors related to ID-checking reported in #10
